[package]
name = "gol_cuda"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
opencl3 = "0.9.3"
rustacuda = "0.1.3"
rustacuda_core = "0.1.2"
rustacuda_derive = "0.1.2"

[dev-dependencies]
criterion = "0.5.1"

[features]
cuda = []
default = ["cuda"]

[profile.release]
opt-level = 3
lto = true
