[package]
name = "gol_cuda"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rust-gpu-tools = {path="rust-gpu-tools", default-features = false, features = ["opencl"] }

[dev-dependencies]
criterion = "0.5.1"

[features]
cuda = ["rust-gpu-tools/cuda"]

[profile.release]
opt-level = 3
lto = true
