[package]
name = "gol_cuda"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
opencl3 = "0.9.3"
cuda-runtime-sys = "0.3.0-alpha.1"

[dev-dependencies]
criterion = "0.5.1"

[features]
cuda = []

[profile.release]
opt-level = 3
lto = true

[[bench]]
name = "gol"
harness = false
