[package]
name = "gol_cuda"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rust-gpu-tools = {version = "0.7.2", default-features = false, features = ["opencl"] }

[features]
cuda = ["rust-gpu-tools/cuda"]