[package]
name = "gol_cuda"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cuda-interface = { git = "https://github.com/binary-banter/cuda-interface", optional = true }
opencl3 = "0.9.3"

[dev-dependencies]
criterion = "0.5.1"

[features]
cuda = ["dep:cuda-interface"]

[profile.release]
opt-level = 3
lto = true

[[bench]]
name = "gol"
harness = false
