[opencl]
# Vertical block dimension (horizontal block dimension is 1).
work-group-size = 256

# Rows computed per thread.
work-per-thread = 3

# Horizontal padding columns (32 cells).
padding-x = 1

# Vertical padding in cells.
padding-y = 16

[cuda]
# Vertical block dimension (horizontal block dimension is 1).
work-group-size = 32

# Rows computed per thread.
work-per-thread = 16

# Steps to simulate at once, must be between 1 and 16.
step-size = 16
