[opencl]
# Vertical block dimension (horizontal block dimension is 1).
work-group-size = 256   # 7900 XTX

# Rows computed per thread.
work-per-thread = 3     # 7900 XTX

# Horizontal padding columns (32 cells).
padding-x = 1           # 7900 XTX

# Vertical padding in cells.
padding-y = 16          # 7900 XTX

[cuda]
# Vertical block dimension (horizontal block dimension is 1).
work-group-size = 32   # 1080Ti

# Rows computed per thread.
work-per-thread = 8     # 1080Ti

# Horizontal padding columns (32 cells).
padding-x = 1           # 1080Ti

# Vertical padding in cells.
padding-y = 16          # 1080Ti
